In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as snb

In [2]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_iris
iris=load_iris()
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
df['target']=iris.target

In [3]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [3]:
x=df.iloc[:,0:4]
y=df.iloc[:,4]

In [4]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)


In [5]:
from sklearn.svm import SVC
svn=SVC()

In [6]:
svn.fit(xtrain,ytrain)

SVC()

In [8]:
prediction=svn.predict(xtest)

In [9]:
prediction

array([2, 0, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 0, 1, 1, 1,
       2, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 2, 0, 0,
       2])

In [10]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,prediction)

array([[ 9,  0,  0],
       [ 0, 15,  2],
       [ 0,  0, 19]], dtype=int64)

In [11]:
accuracy_score(ytest,prediction)

0.9555555555555556

In [11]:
##NOW complte about confusion metrix
#it is 2*2 shape metrix in case of binary classification where we able to check the actual and predicted values.
	      Actual1 Actual0
Predicted1	Tp	fp
Predicted0	Fn	tn
'''now we will have some topic to cover in performance metrix with classification ml technique
these are as below
1.type 1 error-FPR (this error also called false fp, and it is calculated by fp/fp+tn)
2.type 2 error-fnr(this is called false negative rate and it is calclucated by fn/fn+tp)
3.now come to recall(tpr) this is calculated by tp/tp+fn
4.and precision (tnr) this is calcucated by tp/tp+fp
5.fbetascore=(1+b**2)(recall*precision)/b**2(recall+precision)
we assign b value as 1 when fp and fn are equally importtant so called f1 score and formuala will be 2((recall*precision)/(recall+precision)
when fp is more important then we reduce b value as 0.5 and when fn is more important then increase b value as 2

'''


In [25]:
from sklearn.metrics import classification_report
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score,precision_score
classification_report(ytest,prediction)



'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00         9\n           1       1.00      0.88      0.94        17\n           2       0.90      1.00      0.95        19\n\n    accuracy                           0.96        45\n   macro avg       0.97      0.96      0.96        45\nweighted avg       0.96      0.96      0.96        45\n'

In [10]:
from sklearn.model_selection import cross_val_score
cross_val_score(svn,x,y)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

# Cross validation score- types
#there are 7 types of cross_val--1)f-fold,2)hold-out(train test split),3)stratified-k fold,4)leave-p-out,5)leave one #out,6)monte carlo(shuffle-split),7)time series(rolling cross).
from sklearn.model_selection import cross_val_score,KFold,StratifiedKFold,LeavePOut,LeaveOneOut,ShuffleSplit,TimeSeriesSplit
turing.com/kb/differentcrossvalidation

In [13]:
from sklearn.model_selection import cross_val_score,KFold,StratifiedKFold,LeavePOut,LeaveOneOut,ShuffleSplit,TimeSeriesSplit

In [14]:
k_fold=KFold(n_splits=7)
st_kf=StratifiedKFold(n_splits=7)
lpo=LeavePOut(p=1)
loo=LeaveOneOut()
sufflesplit=ShuffleSplit(test_size=0.3,train_size=0.5,n_splits=6)
tscv=TimeSeriesSplit(n_splits=7)

In [28]:
a=cross_val_score(svn,xtrain,ytrain,cv=sufflesplit)

In [29]:
a

array([0.9375 , 1.     , 1.     , 0.96875, 0.9375 , 1.     ])

In [ ]:
##Evaluation metrics to evaluate Classification model

In [ ]:
#Accuracy and its limitation
#Confision metrix
#precision $ recall
#f1 score
#Specificity
#Receiver operating characterisctic curve(roc)
#area under curve(AUc)


In [39]:
from sklearn.datasets import load_wine
wine=load_wine()

In [40]:
df1=pd.DataFrame(wine.data,columns=wine.feature_names)

In [41]:
df1['Target']=wine.target

In [46]:
from sklearn import datasets
#dir(datasets)
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [50]:
wine.DESCR

'.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                     